apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8stest-sample-app
  labels:
    app: k8stester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8stester
      tier: backend
  template:
    metadata:
      labels:
        app: k8stester
        tier: backend
    spec:
      containers:
      - env:
        - name: PORT
          value: "80"
        name: k8stester
        image: khrisl33t/k8stester:v4
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
