apiVersion: v1
kind: Service
metadata:
  name: k8s-tester-service-2
  labels:
    app: k8stester
spec:
  selector:
    app: k8stester
    tier: backend
  ports:
  - port: 80
    targetPort: 3000
  type:
    LoadBalancer
