apiVersion: v1
kind: Service
metadata:
  name: k8s-tester-service
  labels:
    app: k8stester
spec:
  selector:
    app: k8stester
    tier: backend
  ports:
  - port: 80
    targetPort: 80
  type:
    ClusterIP
  # or edit type to LoadBalancer to get an external IP
